language: objective-c
osx_image: xcode12.2
env:
  global:
    - RUBYMOTION_LICENSE=1dcac45cc434293009f74b33037bdf7361a3a1ff # Official license key for open-source projects
    - TMP_DIR=./tmp # For motion repo, so it doesn't attempt to use /tmp, to which it has no access
    - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - (xcrun simctl list)
  - wget http://travisci.rubymotion.com/ -O RubyMotion-TravisCI.pkg
  - sudo installer -pkg RubyMotion-TravisCI.pkg -target /
  - cp -r /usr/lib/swift/*.dylib /Applications/Xcode.app/Contents/Frameworks/
  - touch /Applications/Xcode.app/Contents/Frameworks/.swift-5-staged
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion
  - eval "sudo motion activate $RUBYMOTION_LICENSE"
  - sudo motion update
  - (motion --version)
  - (ruby --version)
  - motion repo
  - bundle install --jobs=3 --retry=3
  - bundle exec rake pod:install

gemfile:
  - Gemfile

jobs:
  include:
    - stage: rubocop
      script: bundle exec rubocop
    - stage: macos
      script: bundle exec rake spec
    # - stage: ios
    #   script: bundle exec rake spec platform=ios
